version: '3.5'
services:
  game:
    image: 'rsoptimum/aresframework-gameengine:Release-v85'
    stdin_open: true
    tty: true
    ports: 
      - "${GAME_PORT}:43594"
    volumes:
      - "${CACHE_LOCATION}:/root/.ares/Cache/"
      - "${PLUGINS_LOCATION}:/root/.ares/Plugins/"