trigger:
  - release
  - dev
  - staging

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:

  - task: CmdLine@2
    displayName: 'Build server'
    timeoutInMinutes: 1
    inputs:
      script: 'make build'

  - task: CmdLine@2
    displayName: 'Run all unit tests'
    timeoutInMinutes: 1
    inputs:
      script: 'make test'