# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- release
- dev
- staging

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:

- task: CmdLine@2
  displayName: 'Build server'
  inputs:
    script: 'make build'

- task: CmdLine@2
  displayName: 'Run all unit tests'
  inputs:
    script: 'make test'