name: $(ENVIRONMENT).$(Build.BuildId)

# We want manual intervention here
trigger: none
pr: none

schedules:
- cron: '0 0 * * SUN'
  displayName: 'Weekly Dev Build'
  branches: 
    include:
    - dev

pool:
  name: Default

steps:
  
  # Builds the server to test
- task: CmdLine@2
  displayName: 'Build server'
  inputs:
    script: 'make build'

- task: CmdLine@2
  displayName: 'Run all unit tests'
  inputs:
    script: 'make test'

- task: CmdLine@2
  displayName: 'Build docker image'
  inputs:
    script: 'make docker-build BUILD_VERSION=$(ENVIRONMENT)-v$(Build.BuildId)'
    
- task: CmdLine@2
  displayName: 'Publish docker image'
  inputs:
    script: 'make docker-publish BUILD_VERSION=$(ENVIRONMENT)-v$(Build.BuildId) DOCKER_TOKEN=$(DOCKER_TOKEN)'
    
- task: CmdLine@2
  displayName: 'Delete docker image'
  inputs:
    script: 'docker image rm rsoptimum/aresframework-gameengine:$(ENVIRONMENT)-v$(Build.BuildId)'